name: GitHub-Profile-3D-Contrib

on:
  schedule:
    # 오전 10시 (KST) = 01:00 UTC
    - cron: "0 1 * * *"
    # 오후 4시 (KST) = 07:00 UTC  
    - cron: "0 7 * * *"
    # 오후 11시 (KST) = 14:00 UTC
    - cron: "0 14 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Generate 3D profile
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          
      - name: Commit & Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add -A .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update 3D profile contribution graph"
            git push
          fi
